import mongoose from 'mongoose';

const applicationPackageSchema = new mongoose.Schema({
  userId: {
    type: String,
    required: true,
    index: true
  },
  jobId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Job',
    required: true
  },
  resumeId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Resume'
  },
  coverLetterId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'CoverLetter'
  },
  portfolioUrl: {
    type: String,
    trim: true
  },
  additionalDocuments: [{
    name: String,
    url: String,
    type: String
  }],
  status: {
    type: String,
    enum: ['draft', 'ready', 'scheduled', 'submitted', 'failed'],
    default: 'draft'
  },
  scheduledFor: {
    type: Date
  },
  submittedAt: {
    type: Date
  },
  metadata: {
    companyName: String,
    jobTitle: String,
    applicationUrl: String,
    notes: String
  },
  autoGenerated: {
    type: Boolean,
    default: false
  },
  generationSettings: {
    resumeTemplate: String,
    coverLetterTemplate: String,
    tailoredForJob: Boolean
  }
}, {
  timestamps: true
});

// Indexes for efficient querying
applicationPackageSchema.index({ userId: 1, status: 1 });
applicationPackageSchema.index({ userId: 1, jobId: 1 });
applicationPackageSchema.index({ scheduledFor: 1, status: 1 });

export const ApplicationPackage = mongoose.model('ApplicationPackage', applicationPackageSchema);
