import mongoose from 'mongoose';

const relationshipReminderSchema = new mongoose.Schema({
  userId: {
    type: String,
    required: true,
    index: true
  },
  contactId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Contact',
    required: true,
    index: true
  },
  reminderType: {
    type: String,
    enum: [
      'General Check-in',
      'Birthday',
      'Work Anniversary',
      'Industry News Share',
      'Congratulations',
      'Thank You',
      'Follow-up',
      'Coffee Chat',
      'Relationship Maintenance',
      'Custom'
    ],
    required: true
  },
  reminderDate: {
    type: Date,
    required: true,
    index: true
  },
  priority: {
    type: String,
    enum: ['High', 'Medium', 'Low'],
    default: 'Medium'
  },
  title: {
    type: String,
    required: true,
    trim: true
  },
  description: {
    type: String,
    trim: true
  },
  suggestedMessage: {
    type: String,
    trim: true
  },
  status: {
    type: String,
    enum: ['Pending', 'Completed', 'Dismissed', 'Snoozed'],
    default: 'Pending',
    index: true
  },
  completedAt: {
    type: Date
  },
  completedNotes: {
    type: String,
    trim: true
  },
  snoozedUntil: {
    type: Date
  },
  isRecurring: {
    type: Boolean,
    default: false
  },
  recurrencePattern: {
    type: String,
    enum: ['Daily', 'Weekly', 'Biweekly', 'Monthly', 'Quarterly', 'Yearly', 'Custom'],
    default: null
  },
  recurrenceInterval: {
    type: Number, // Custom interval in days
    default: null
  },
  nextRecurrenceDate: {
    type: Date
  },
  autoGenerated: {
    type: Boolean,
    default: false
  },
  generationReason: {
    type: String,
    trim: true
  },
  relatedIndustryNews: [{
    title: String,
    url: String,
    source: String,
    relevance: String
  }],
  templateUsed: {
    type: String,
    trim: true
  },
  engagementMetrics: {
    opened: { type: Boolean, default: false },
    openedAt: Date,
    responseReceived: { type: Boolean, default: false },
    responseReceivedAt: Date,
    interactionLogged: { type: Boolean, default: false }
  }
}, {
  timestamps: true
});

// Indexes for efficient queries
relationshipReminderSchema.index({ userId: 1, status: 1, reminderDate: 1 });
relationshipReminderSchema.index({ userId: 1, contactId: 1, status: 1 });
relationshipReminderSchema.index({ userId: 1, reminderType: 1 });

// Method to mark reminder as completed
relationshipReminderSchema.methods.complete = async function(notes) {
  this.status = 'Completed';
  this.completedAt = new Date();
  if (notes) this.completedNotes = notes;
  
  // If recurring, create next reminder
  if (this.isRecurring && this.nextRecurrenceDate) {
    const nextReminder = new this.constructor({
      userId: this.userId,
      contactId: this.contactId,
      reminderType: this.reminderType,
      reminderDate: this.nextRecurrenceDate,
      priority: this.priority,
      title: this.title,
      description: this.description,
      suggestedMessage: this.suggestedMessage,
      isRecurring: this.isRecurring,
      recurrencePattern: this.recurrencePattern,
      recurrenceInterval: this.recurrenceInterval,
      autoGenerated: this.autoGenerated,
      templateUsed: this.templateUsed
    });
    
    // Calculate next recurrence
    if (this.recurrencePattern === 'Custom' && this.recurrenceInterval) {
      nextReminder.nextRecurrenceDate = new Date(this.nextRecurrenceDate);
      nextReminder.nextRecurrenceDate.setDate(nextReminder.nextRecurrenceDate.getDate() + this.recurrenceInterval);
    } else {
      nextReminder.nextRecurrenceDate = calculateNextRecurrence(this.nextRecurrenceDate, this.recurrencePattern);
    }
    
    await nextReminder.save();
  }
  
  return this.save();
};

// Method to snooze reminder
relationshipReminderSchema.methods.snooze = async function(days) {
  this.status = 'Snoozed';
  const snoozeDate = new Date();
  snoozeDate.setDate(snoozeDate.getDate() + days);
  this.snoozedUntil = snoozeDate;
  return this.save();
};

// Helper function to calculate next recurrence
function calculateNextRecurrence(currentDate, pattern) {
  const next = new Date(currentDate);
  switch (pattern) {
    case 'Daily':
      next.setDate(next.getDate() + 1);
      break;
    case 'Weekly':
      next.setDate(next.getDate() + 7);
      break;
    case 'Biweekly':
      next.setDate(next.getDate() + 14);
      break;
    case 'Monthly':
      next.setMonth(next.getMonth() + 1);
      break;
    case 'Quarterly':
      next.setMonth(next.getMonth() + 3);
      break;
    case 'Yearly':
      next.setFullYear(next.getFullYear() + 1);
      break;
  }
  return next;
}

const RelationshipReminder = mongoose.model('RelationshipReminder', relationshipReminderSchema);

export default RelationshipReminder;
