import { describe, it, expect, beforeAll } from '@jest/globals';

let ApplicationPackage;

beforeAll(async () => {
  // import the model module; does not require a DB connection to inspect schema
  ApplicationPackage = (await import('../ApplicationPackage.js')).ApplicationPackage;
});

describe('ApplicationPackage model schema', () => {
  it('has the correct model name', () => {
    expect(ApplicationPackage.modelName).toBe('ApplicationPackage');
  });

  it('defines required and indexed fields and options', () => {
    const schema = ApplicationPackage.schema;

    // userId required and indexed
    const userPath = schema.path('userId');
    expect(userPath).toBeDefined();
    expect(userPath.options.required).toBe(true);

    // jobId is an ObjectId ref to Job
    const jobPath = schema.path('jobId');
    expect(jobPath).toBeDefined();
    expect(jobPath.options.ref).toBe('Job');

    // portfolioUrl should trim
    const portfolio = schema.path('portfolioUrl');
    expect(portfolio).toBeDefined();
    expect(portfolio.options.trim).toBe(true);

    // additionalDocuments should be an array type
    const additional = schema.path('additionalDocuments');
    expect(additional).toBeDefined();
    expect(additional.instance).toBe('Array');

    // status enum and default
    const status = schema.path('status');
    expect(status).toBeDefined();
    expect(status.enumValues).toEqual(expect.arrayContaining(['draft','ready','scheduled','submitted','failed']));
    expect(status.options.default).toBe('draft');

    // autoGenerated default
    const auto = schema.path('autoGenerated');
    expect(auto).toBeDefined();
    expect(auto.options.default).toBe(false);

    // generationSettings fields exist on the schema tree (nested object)
    expect(schema.tree.generationSettings).toBeDefined();
    // timestamps option enabled
    expect(schema.options.timestamps).toBeTruthy();
  });

  it('registers the expected indexes', () => {
    const indexes = ApplicationPackage.schema._indexes.map(([spec]) => spec);

    // helper to find an index spec by keys
    const hasIndex = (keys) => indexes.some((idx) => {
      const idxKeys = Object.keys(idx).join(',');
      return keys.split(',').every(k => idxKeys.includes(k));
    });

    expect(hasIndex('userId,status')).toBe(true);
    expect(hasIndex('userId,jobId')).toBe(true);
    expect(hasIndex('scheduledFor,status')).toBe(true);
  });
});
